backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images/paintings'
public_folder: '/assets/images/paintings'

collections:
  - name: 'paintings'
    label: 'Paintings'
    folder: 'src/paintings'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'painting.njk',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'number' }
      - { label: 'Size', name: 'size', widget: 'string' }
      - {
          label: 'Medium',
          name: 'medium',
          widget: 'string',
          default: 'Oil on canvas',
        }
      - {
          label: 'Availability',
          name: 'availability',
          widget: 'select',
          options: ['Available', 'Sold'],
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
